name: linkstatus

on: [push, pull_request]

jobs:
  pre-commit:
    name: Code Quality Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit run -a